In [1]:

import warnings # import warnings library to handle warning messages
warnings.filterwarnings("ignore")# Ignore all warnings

import numpy as np # import numpy library for numerical operations
import pandas as pd # import pandas library for data manipulation and analysis
import matplotlib.pyplot as plt # import matplotlib library for data visualization
import seaborn as sns # import seaborn library for statistical data visualization

from sklearn.impute import SimpleImputer # import SimpleImputer class from sklearn.
#impute module for handling missing values 

from sklearn.preprocessing import StandardScaler # import StandardScaler class from sklearn. 
# preprocessing module for feature scaling

from sklearn.cluster import KMeans # import KMeans class from sklearn. cluster module for clustering analysis

from sklearn.decomposition import PCA # import PCA class from sklearn. 
# decomposition module for dimensionality reduction

from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
 # import metrics for evaluating clustering performance

from IPython.display import display # import display function from IPython.
#display module for displaying dataframes in Jupyter notebooks

In [2]:
sns.set_theme(style="whitegrid", palette="Set2")
RANDOM_STATE = 42

df = pd.read_csv(r"D:\Guvi\Project\Project_4\app_user_behavior_dataset.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (50000, 25)

,user_id,age,gender,country,device_type,app_version,sessions_per_week,avg_session_duration_min,daily_active_minutes,feature_clicks_per_session,...,days_since_last_login,subscription_type,ads_clicked_last_30_days,content_downloads,social_shares,rating_given,churn_risk_score,engagement_score,account_age_days,marketing_source
0,100000,56,Female,India,iOS,2.1,5,3.41,52.71,13,...,20,Basic,9,5,2,NaN,0.31,55.79,1152,Referral
1,100001,46,Male,UK,iOS,1.0,8,24.44,42.03,7,...,7,Free,8,3,3,3.0,0.87,82.39,1059,Email Campaign
2,100002,32,Female,UK,iOS,1.2,12,5.34,76.69,7,...,33,Free,11,6,1,2.0,0.63,42.49,678,Google Ads
3,100003,25,Male,India,Android,2.0,5,3.98,65.38,16,...,17,Basic,6,3,1,3.0,0.43,62.81,92,Organic
4,100004,38,Male,Australia,Android,1.0,10,12.85,57.06,13,...,21,Basic,4,4,2,5.0,0.43,38.21,772,Email Campaign

In [3]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
display(df.dtypes.to_frame("Data Type"))

Column names:
['user_id', 'age', 'gender', 'country', 'device_type', 'app_version', 'sessions_per_week', 'avg_session_duration_min', 'daily_active_minutes', 'feature_clicks_per_session', 'notifications_opened_per_week', 'in_app_search_count', 'pages_viewed_per_session', 'crash_events_last_30_days', 'support_tickets_raised', 'days_since_last_login', 'subscription_type', 'ads_clicked_last_30_days', 'content_downloads', 'social_shares', 'rating_given', 'churn_risk_score', 'engagement_score', 'account_age_days', 'marketing_source']

Data types:

                              Data Type
user_id                           int64
age                               int64
gender                           object
country                          object
device_type                      object
app_version                     float64
sessions_per_week                 int64
avg_session_duration_min        float64
daily_active_minutes            float64
feature_clicks_per_session        int64
notifications_opened_per_week     int64
in_app_search_count               int64
pages_viewed_per_session          int64
crash_events_last_30_days         int64
support_tickets_raised            int64
days_since_last_login             int64
subscription_type                object
ads_clicked_last_30_days          int64
content_downloads                 int64
social_shares                     int64
rating_given                    float64
churn_risk_score                float64
engagement_score                float64
account_age_days                  int64
marketing_source                 object

In [ ]:

import warnings # import warnings library to handle warning messages
warnings.filterwarnings("ignore")# Ignore all warnings

import numpy as np # import numpy library for numerical operations
import pandas as pd # import pandas library for data manipulation and analysis
import matplotlib.pyplot as plt # import matplotlib library for data visualization
import seaborn as sns # import seaborn library for statistical data visualization

from sklearn.impute import SimpleImputer # import SimpleImputer class from sklearn.
#impute module for handling missing values 

from sklearn.preprocessing import StandardScaler # import StandardScaler class from sklearn. 
# preprocessing module for feature scaling

from sklearn.cluster import KMeans # import KMeans class from sklearn. cluster module for clustering analysis

from sklearn.decomposition import PCA # import PCA class from sklearn. 
# decomposition module for dimensionality reduction

from sklearn.metrics import silhouette_score, davies_bouldin_score, calinski_harabasz_score
 # import metrics for evaluating clustering performance

from IPython.display import display # import display function from IPython.
#display module for displaying dataframes in Jupyter notebooks

In [ ]:
sns.set_theme(style="whitegrid", palette="Set2")
RANDOM_STATE = 42

df = pd.read_csv(r"D:\Guvi\Project\Project_4\app_user_behavior_dataset.csv")

print("Dataset shape:", df.shape)
display(df.head())

Dataset shape: (50000, 25)

,user_id,age,gender,country,device_type,app_version,sessions_per_week,avg_session_duration_min,daily_active_minutes,feature_clicks_per_session,...,days_since_last_login,subscription_type,ads_clicked_last_30_days,content_downloads,social_shares,rating_given,churn_risk_score,engagement_score,account_age_days,marketing_source
0,100000,56,Female,India,iOS,2.1,5,3.41,52.71,13,...,20,Basic,9,5,2,NaN,0.31,55.79,1152,Referral
1,100001,46,Male,UK,iOS,1.0,8,24.44,42.03,7,...,7,Free,8,3,3,3.0,0.87,82.39,1059,Email Campaign
2,100002,32,Female,UK,iOS,1.2,12,5.34,76.69,7,...,33,Free,11,6,1,2.0,0.63,42.49,678,Google Ads
3,100003,25,Male,India,Android,2.0,5,3.98,65.38,16,...,17,Basic,6,3,1,3.0,0.43,62.81,92,Organic
4,100004,38,Male,Australia,Android,1.0,10,12.85,57.06,13,...,21,Basic,4,4,2,5.0,0.43,38.21,772,Email Campaign

In [ ]:
print("Column names:")
print(df.columns.tolist())

print("\nData types:")
display(df.dtypes.to_frame("Data Type"))

Column names:
['user_id', 'age', 'gender', 'country', 'device_type', 'app_version', 'sessions_per_week', 'avg_session_duration_min', 'daily_active_minutes', 'feature_clicks_per_session', 'notifications_opened_per_week', 'in_app_search_count', 'pages_viewed_per_session', 'crash_events_last_30_days', 'support_tickets_raised', 'days_since_last_login', 'subscription_type', 'ads_clicked_last_30_days', 'content_downloads', 'social_shares', 'rating_given', 'churn_risk_score', 'engagement_score', 'account_age_days', 'marketing_source']

Data types:

                              Data Type
user_id                           int64
age                               int64
gender                           object
country                          object
device_type                      object
app_version                     float64
sessions_per_week                 int64
avg_session_duration_min        float64
daily_active_minutes            float64
feature_clicks_per_session        int64
notifications_opened_per_week     int64
in_app_search_count               int64
pages_viewed_per_session          int64
crash_events_last_30_days         int64
support_tickets_raised            int64
days_since_last_login             int64
subscription_type                object
ads_clicked_last_30_days          int64
content_downloads                 int64
social_shares                     int64
rating_given                    float64
churn_risk_score                float64
engagement_score                float64
account_age_days                  int64
marketing_source                 object

In [ ]:
print("\nMissing values:")
display(df.isnull().sum().to_frame("Missing Values"))

print("\nStatistical summary:")
display(df.describe(include="all").T)

In [ ]:
ID_COLUMN = "user_id"

NUMERIC_COLUMNS = [
    "age",
    "sessions_per_week",
    "avg_session_duration_min",
    "daily_active_minutes",
    "feature_clicks_per_session",
    "notifications_opened_per_week",
    "in_app_search_count",
    "pages_viewed_per_session",
    "crash_events_last_30_days",
    "support_tickets_raised",
    "days_since_last_login",
    "ads_clicked_last_30_days",
    "content_downloads",
    "social_shares"
]

CATEGORICAL_COLUMNS = [
    "gender",
    "country",
    "device_type",
    "app_version",
    "subscription_type"
]

In [ ]:
EXPECTED_COLUMNS = [ID_COLUMN] + NUMERIC_COLUMNS + CATEGORICAL_COLUMNS

missing_columns = [col for col in EXPECTED_COLUMNS if col not in df.columns]

if missing_columns:
    raise ValueError(f"Missing columns: {missing_columns}")

print("All expected columns are available.")

print (f"Missing columns: {missing_columns}")

In [ ]:
df_clean = df.copy()

# Convert empty strings into missing values
df_clean = df_clean.replace(r"^\s*$", np.nan, regex=True) 

# Check duplicate users
duplicate_users = df_clean.duplicated(subset=ID_COLUMN).sum()
print("Duplicate user IDs before cleaning:", duplicate_users)

In [ ]:
# Keep one record per user
df_clean = df_clean.drop_duplicates(subset=ID_COLUMN, keep="first")

# Convert numeric columns safely to numbers
for col in NUMERIC_COLUMNS:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

print("\nMissing values before filling:")
display(df_clean.isnull().sum().to_frame("Missing Values"))

# Fill numerical missing values using median
numeric_imputer = SimpleImputer(strategy="median")
df_clean[NUMERIC_COLUMNS] = numeric_imputer.fit_transform(df_clean[NUMERIC_COLUMNS])

# Fill categorical missing values using the most common value
for col in CATEGORICAL_COLUMNS:
    if df_clean[col].isnull().sum() > 0:
        most_common_value = df_clean[col].mode()[0]
        df_clean[col] = df_clean[col].fillna(most_common_value)

print("\nMissing values after cleaning:")
display(df_clean.isnull().sum().to_frame("Missing Values"))

print("\nCleaned dataset shape:", df_clean.shape)

In [ ]:
df_engineered = df_clean.copy()

# Combines several interaction signals into one meaningful feature.
df_engineered["interaction_depth_per_session"] = (
    df_engineered["feature_clicks_per_session"] # Number of feature clicks per session
    + df_engineered["pages_viewed_per_session"] # Number of pages viewed per session
    + df_engineered["in_app_search_count"] # Number of in-app searches per session
)

# Use selected behavior-related features for K-Means.
MODEL_FEATURES = [
    "sessions_per_week",
    "avg_session_duration_min",
    "daily_active_minutes",
    "interaction_depth_per_session",
    "notifications_opened_per_week",
    "days_since_last_login",
    "ads_clicked_last_30_days",
    "content_downloads",
    "social_shares"
]

print("Selected model features:")
print(MODEL_FEATURES)

display(df_engineered[MODEL_FEATURES].head())

In [ ]:
df_model = df_engineered.copy() # Create a copy of the engineered dataframe for modeling

# Cap extreme values at the 1st and 99th percentiles.
lower_limits = df_model[MODEL_FEATURES].quantile(0.01) # Calculate the 1st percentile for each feature in MODEL_FEATURES
upper_limits = df_model[MODEL_FEATURES].quantile(0.99) # Calculate the 99th percentile for each feature in MODEL_FEATURES

for col in MODEL_FEATURES:
    df_model[col] = df_model[col].clip(
        lower=lower_limits[col],
        upper=upper_limits[col]
    )

print("Outlier capping completed.")

In [ ]:
fig, axes = plt.subplots(3, 3, figsize=(18, 14))
axes = axes.flatten()

for i, col in enumerate(MODEL_FEATURES):
    sns.histplot(
        data=df_engineered, # Use the original engineered dataframe for visualization
        x=col, # Use the feature column for the x-axis
        bins=40, # Number of bins for the histogram
        kde=True, # Kernel Density Estimate for smooth distribution curve 
        color="steelblue", # Color of the histogram bars
        ax=axes[i] # Use the corresponding subplot for the histogram
    )
    axes[i].set_title(f"Distribution of {col}")

plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(16, 7))

sns.boxplot(
    data=df_engineered[MODEL_FEATURES],
    orient="h", # Horizontal orientation for better readability
    palette="Set1" # Color palette for the boxplots
)

plt.title("Outlier Analysis of Behavioral Features")
plt.xlabel("Value")
plt.show()

In [ ]:
correlation_matrix = df_engineered[MODEL_FEATURES].corr() # Calculate the correlation matrix for the selected model features

plt.figure(figsize=(12, 8)) # Set the figure size for the heatmap

sns.heatmap(
    correlation_matrix,
    annot=True, # Annotate the heatmap with correlation coefficients
    cmap="coolwarm", # Color map for the heatmap
    fmt=".2f", # Format for the annotation text
    linewidths=0.5 # Width of the lines that will divide each cell in the heatmap
)

plt.title("Correlation Matrix of Selected Behavior Features")
plt.show()

In [ ]:
X = df_model[MODEL_FEATURES].copy()

# Detect highly skewed non-negative features and apply log transformation.
skewness = X.skew()

LOG_TRANSFORM_FEATURES = [
    col for col in MODEL_FEATURES # List comprehension to identify features that are non-negative and highly skewed
    if X[col].min() >= 0 and abs(skewness[col]) > 1 # Check for non-negative and highly skewed features
]

for col in LOG_TRANSFORM_FEATURES: # Apply log transformation to the identified features
    X[col] = np.log1p(X[col]) # Apply log(1+x) transformation to reduce skewness

print("Log-transformed features:") 
print(LOG_TRANSFORM_FEATURES)

# Standardize all features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=MODEL_FEATURES
)

display(X_scaled_df.head())

In [ ]:
k_values = range(2, 9)

inertia_scores = []
silhouette_scores = []
davies_bouldin_scores = []
calinski_harabasz_scores = [] # Initialize lists to store evaluation metrics for each k value

sample_size = min(10000, len(X_scaled)) # Set the sample size for evaluation
rng = np.random.default_rng(RANDOM_STATE) # Initialize a random number generator with a fixed seed for reproducibility

sample_indices = rng.choice( # Select a random sample of indices for evaluation 
    len(X_scaled), # Total number of samples in the dataset
    size=sample_size,
    replace=False
)

for k in k_values:
    kmeans_test = KMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        n_init=20
    )

    labels_test = kmeans_test.fit_predict(X_scaled)

    inertia_scores.append(kmeans_test.inertia_)

    silhouette_scores.append(
        silhouette_score(
            X_scaled[sample_indices],
            labels_test[sample_indices]
        )
    )

    davies_bouldin_scores.append(
        davies_bouldin_score(X_scaled, labels_test)
    )

    calinski_harabasz_scores.append(
        calinski_harabasz_score(X_scaled, labels_test)
    )

evaluation_results = pd.DataFrame({
    "k": list(k_values), 
    "inertia": inertia_scores,
    "silhouette_score": silhouette_scores,
    "davies_bouldin_score": davies_bouldin_scores,
    "calinski_harabasz_score": calinski_harabasz_scores
})

display(evaluation_results)

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

axes[0].plot(
    list(k_values),
    inertia_scores,
    marker="o",
    linewidth=2,
    color="royalblue"
)
axes[0].set_title("Elbow Method")
axes[0].set_xlabel("Number of Clusters")
axes[0].set_ylabel("Inertia")
axes[0].set_xticks(list(k_values))

axes[1].plot(
    list(k_values),
    silhouette_scores,
    marker="o",
    linewidth=2,
    color="green"
)
axes[1].set_title("Silhouette Score by K")
axes[1].set_xlabel("Number of Clusters")
axes[1].set_ylabel("Silhouette Score")
axes[1].set_xticks(list(k_values))

plt.tight_layout()
plt.show()

In [ ]:
OPTIMAL_K = 4 # Set the optimal number of clusters based on evaluation metrics

kmeans = KMeans(
    n_clusters=OPTIMAL_K,
    random_state=RANDOM_STATE,
    n_init=20
)

final_labels = kmeans.fit_predict(X_scaled) # Assign cluster labels to each user based on the final K-Means model

df_results = df_engineered.copy()
df_results["cluster_id"] = final_labels

print("Final K-Means model completed.")

display(
    df_results["cluster_id"]
    .value_counts()
    .sort_index()
    .to_frame("Number of Users")
)

In [ ]:
final_silhouette = silhouette_score(
    X_scaled[sample_indices],
    final_labels[sample_indices]
)

final_davies_bouldin = davies_bouldin_score(
    X_scaled,
    final_labels
)

final_calinski_harabasz = calinski_harabasz_score(
    X_scaled,
    final_labels
)

print("Final Model Evaluation")
print("-" * 35)
print(f"Number of clusters: {OPTIMAL_K}")
print(f"Inertia: {kmeans.inertia_:.2f}")
print(f"Silhouette Score: {final_silhouette:.4f}")
print(f"Davies-Bouldin Score: {final_davies_bouldin:.4f}")
print(f"Calinski-Harabasz Score: {final_calinski_harabasz:.2f}")

In [ ]:
cluster_profile = (
    df_results
    .groupby("cluster_id")[MODEL_FEATURES] # Group the results by cluster_id and select the model features for aggregation
    .mean()                                 # Calculate the mean of each feature for each cluster
    .round(2)                               # Round the mean values to 2 decimal places for better readability
)

cluster_counts = (
    df_results["cluster_id"]
    .value_counts()
    .sort_index()
    .rename("user_count")
)

cluster_profile.insert(
    0,
    "user_count",
    cluster_counts
)

print("Cluster behavior profile:")
display(cluster_profile)

In [ ]:
# All features except recency are considered positive engagement signals.
positive_features = [
    "sessions_per_week",
    "avg_session_duration_min",
    "daily_active_minutes",
    "interaction_depth_per_session",
    "notifications_opened_per_week",
    "ads_clicked_last_30_days",
    "content_downloads",
    "social_shares"
]

cluster_z_profile = (
    X_scaled_df
    .assign(cluster_id=final_labels)
    .groupby("cluster_id")
    .mean()
)

# A high days_since_last_login value means lower engagement.
cluster_engagement_score = (
    cluster_z_profile[positive_features].mean(axis=1)
    - cluster_z_profile["days_since_last_login"]
)

cluster_engagement_score = cluster_engagement_score.sort_values()

print("Cluster engagement ranking:")
display(cluster_engagement_score.to_frame("engagement_score"))

ordered_clusters = cluster_engagement_score.index.tolist()

CLUSTER_NAME_MAP = {
    ordered_clusters[0]: "Low Engagement / At-Risk Users",
    ordered_clusters[1]: "Occasional Users",
    ordered_clusters[2]: "Moderate Engagement Users",
    ordered_clusters[3]: "High Engagement Users"
}

df_results["segment"] = df_results["cluster_id"].map(CLUSTER_NAME_MAP)

print(CLUSTER_NAME_MAP)

In [ ]:
pca = PCA(n_components=2, random_state=RANDOM_STATE)
pca_components = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(
    pca_components,
    columns=["PCA_1", "PCA_2"]
)

pca_df["segment"] = df_results["segment"].values

print(
    "Variance explained by PCA:",
    round(pca.explained_variance_ratio_.sum() * 100, 2),
    "%"
)

plot_sample_size = min(10000, len(pca_df))

pca_plot_df = pca_df.sample(
    n=plot_sample_size,
    random_state=RANDOM_STATE
)

plt.figure(figsize=(12, 8))

sns.scatterplot(
    data=pca_plot_df,
    x="PCA_1",
    y="PCA_2",
    hue="segment",
    alpha=0.65,
    s=35,
    palette="Set1"
)

plt.title("PCA Visualization of User Segments")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(title="Segment")
plt.show()

In [ ]:
for col in ["gender", "country", "device_type", "subscription_type"]:
    print(f"\nCluster distribution by {col}:")
    
    profile_table = pd.crosstab(
        df_results["segment"],
        df_results[col],
        normalize="index"
    ).mul(100).round(2)

    display(profile_table)

In [ ]:
users_by_segment = {}

for segment_name in df_results["segment"].unique():
    user_list = df_results.loc[
        df_results["segment"] == segment_name,
        ID_COLUMN
    ].tolist()

    users_by_segment[segment_name] = user_list

    print(f"\n{segment_name}")
    print("Number of users:", len(user_list))
    print("First 20 user IDs:", user_list[:20])

In [ ]:
business_actions = {
    "High Engagement Users": (
        "Offer loyalty rewards, premium plans, referral benefits, "
        "exclusive features, and early product access."
    ),
    "Moderate Engagement Users": (
        "Send personalized feature suggestions, content recommendations, "
        "and targeted notifications to increase engagement."
    ),
    "Low Engagement / At-Risk Users": (
        "Use retention campaigns, onboarding reminders, discounts, "
        "support outreach, and re-engagement notifications."
    ),
    "Occasional Users": (
        "Send timely reminders, simple feature guides, "
        "and personalized content to build regular usage habits."
    )
}

segment_summary = (
    df_results
    .groupby(["cluster_id", "segment"])
    .size()
    .reset_index(name="number_of_users")
)

segment_summary["business_action"] = (
    segment_summary["segment"].map(business_actions)
)

display(segment_summary)

In [ ]:
plt.figure(figsize=(11, 6))

sns.countplot(
    data=df_results,
    x="segment",
    order=df_results["segment"].value_counts().index,
    palette="Set2"
)

plt.title("Number of Users in Each Segment")
plt.xlabel("User Segment")
plt.ylabel("Number of Users")
plt.xticks(rotation=15)
plt.show()

In [ ]:
print("\nMissing values:")
display(df.isnull().sum().to_frame("Missing Values"))

print("\nStatistical summary:")
display(df.describe(include="all").T)

In [ ]:
ID_COLUMN = "user_id"

NUMERIC_COLUMNS = [
    "age",
    "sessions_per_week",
    "avg_session_duration_min",
    "daily_active_minutes",
    "feature_clicks_per_session",
    "notifications_opened_per_week",
    "in_app_search_count",
    "pages_viewed_per_session",
    "crash_events_last_30_days",
    "support_tickets_raised",
    "days_since_last_login",
    "ads_clicked_last_30_days",
    "content_downloads",
    "social_shares"
]

CATEGORICAL_COLUMNS = [
    "gender",
    "country",
    "device_type",
    "app_version",
    "subscription_type"
]

In [ ]:
EXPECTED_COLUMNS = [ID_COLUMN] + NUMERIC_COLUMNS + CATEGORICAL_COLUMNS

missing_columns = [col for col in EXPECTED_COLUMNS if col not in df.columns]

if missing_columns:
    raise ValueError(f"Missing columns: {missing_columns}")

print("All expected columns are available.")

print (f"Missing columns: {missing_columns}")

In [ ]:
df_clean = df.copy()

# Convert empty strings into missing values
df_clean = df_clean.replace(r"^\s*$", np.nan, regex=True)

# Check duplicate users
duplicate_users = df_clean.duplicated(subset=ID_COLUMN).sum()
print("Duplicate user IDs before cleaning:", duplicate_users)

In [ ]:
# Keep one record per user
df_clean = df_clean.drop_duplicates(subset=ID_COLUMN, keep="first")

# Convert numeric columns safely to numbers
for col in NUMERIC_COLUMNS:
    df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

print("\nMissing values before filling:")
display(df_clean.isnull().sum().to_frame("Missing Values"))

# Fill numerical missing values using median
numeric_imputer = SimpleImputer(strategy="median")
df_clean[NUMERIC_COLUMNS] = numeric_imputer.fit_transform(df_clean[NUMERIC_COLUMNS])

# Fill categorical missing values using the most common value
for col in CATEGORICAL_COLUMNS:
    if df_clean[col].isnull().sum() > 0:
        most_common_value = df_clean[col].mode()[0]
        df_clean[col] = df_clean[col].fillna(most_common_value)

print("\nMissing values after cleaning:")
display(df_clean.isnull().sum().to_frame("Missing Values"))

print("\nCleaned dataset shape:", df_clean.shape)

In [ ]:
df_engineered = df_clean.copy()

# Combines several interaction signals into one meaningful feature.
df_engineered["interaction_depth_per_session"] = (
    df_engineered["feature_clicks_per_session"] # Number of feature clicks per session
    + df_engineered["pages_viewed_per_session"] # Number of pages viewed per session
    + df_engineered["in_app_search_count"] # Number of in-app searches per session
)

# Use selected behavior-related features for K-Means.
MODEL_FEATURES = [
    "sessions_per_week",
    "avg_session_duration_min",
    "daily_active_minutes",
    "interaction_depth_per_session",
    "notifications_opened_per_week",
    "days_since_last_login",
    "ads_clicked_last_30_days",
    "content_downloads",
    "social_shares"
]

print("Selected model features:")
print(MODEL_FEATURES)

display(df_engineered[MODEL_FEATURES].head())

In [ ]:
df_model = df_engineered.copy() # Create a copy of the engineered dataframe for modeling

# Cap extreme values at the 1st and 99th percentiles.
lower_limits = df_model[MODEL_FEATURES].quantile(0.01) # Calculate the 1st percentile for each feature in MODEL_FEATURES
upper_limits = df_model[MODEL_FEATURES].quantile(0.99) # Calculate the 99th percentile for each feature in MODEL_FEATURES

for col in MODEL_FEATURES:
    df_model[col] = df_model[col].clip(
        lower=lower_limits[col],
        upper=upper_limits[col]
    )

print("Outlier capping completed.")

In [ ]:
fig, axes = plt.subplots(3, 3, figsize=(18, 14))
axes = axes.flatten()

for i, col in enumerate(MODEL_FEATURES):
    sns.histplot(
        data=df_engineered, # Use the original engineered dataframe for visualization
        x=col, # Use the feature column for the x-axis
        bins=40, # Number of bins for the histogram
        kde=True, # Kernel Density Estimate for smooth distribution curve 
        color="steelblue", # Color of the histogram bars
        ax=axes[i] # Use the corresponding subplot for the histogram
    )
    axes[i].set_title(f"Distribution of {col}")

plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(16, 7))

sns.boxplot(
    data=df_engineered[MODEL_FEATURES],
    orient="h", # Horizontal orientation for better readability
    palette="Set1" # Color palette for the boxplots
)

plt.title("Outlier Analysis of Behavioral Features")
plt.xlabel("Value")
plt.show()

In [ ]:
correlation_matrix = df_engineered[MODEL_FEATURES].corr() # Calculate the correlation matrix for the selected model features

plt.figure(figsize=(12, 8)) # Set the figure size for the heatmap

sns.heatmap(
    correlation_matrix,
    annot=True, # Annotate the heatmap with correlation coefficients
    cmap="coolwarm", # Color map for the heatmap
    fmt=".2f", # Format for the annotation text
    linewidths=0.5 # Width of the lines that will divide each cell in the heatmap
)

plt.title("Correlation Matrix of Selected Behavior Features")
plt.show()

In [ ]:
X = df_model[MODEL_FEATURES].copy()

# Detect highly skewed non-negative features and apply log transformation.
skewness = X.skew()

LOG_TRANSFORM_FEATURES = [
    col for col in MODEL_FEATURES # List comprehension to identify features that are non-negative and highly skewed
    if X[col].min() >= 0 and abs(skewness[col]) > 1 # Check for non-negative and highly skewed features
]

for col in LOG_TRANSFORM_FEATURES: # Apply log transformation to the identified features
    X[col] = np.log1p(X[col]) # Apply log(1+x) transformation to reduce skewness

print("Log-transformed features:") 
print(LOG_TRANSFORM_FEATURES)

# Standardize all features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled_df = pd.DataFrame(
    X_scaled,
    columns=MODEL_FEATURES
)

display(X_scaled_df.head())

In [ ]:
k_values = range(2, 9)

inertia_scores = []
silhouette_scores = []
davies_bouldin_scores = []
calinski_harabasz_scores = [] # Initialize lists to store evaluation metrics for each k value

sample_size = min(10000, len(X_scaled)) # Set the sample size for evaluation
rng = np.random.default_rng(RANDOM_STATE) # Initialize a random number generator with a fixed seed for reproducibility

sample_indices = rng.choice( # Select a random sample of indices for evaluation 
    len(X_scaled), # Total number of samples in the dataset
    size=sample_size,
    replace=False
)

for k in k_values:
    kmeans_test = KMeans(
        n_clusters=k,
        random_state=RANDOM_STATE,
        n_init=20
    )

    labels_test = kmeans_test.fit_predict(X_scaled)

    inertia_scores.append(kmeans_test.inertia_)

    silhouette_scores.append(
        silhouette_score(
            X_scaled[sample_indices],
            labels_test[sample_indices]
        )
    )

    davies_bouldin_scores.append(
        davies_bouldin_score(X_scaled, labels_test)
    )

    calinski_harabasz_scores.append(
        calinski_harabasz_score(X_scaled, labels_test)
    )

evaluation_results = pd.DataFrame({
    "k": list(k_values), 
    "inertia": inertia_scores,
    "silhouette_score": silhouette_scores,
    "davies_bouldin_score": davies_bouldin_scores,
    "calinski_harabasz_score": calinski_harabasz_scores
})

display(evaluation_results)

In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

axes[0].plot(
    list(k_values),
    inertia_scores,
    marker="o",
    linewidth=2,
    color="royalblue"
)
axes[0].set_title("Elbow Method")
axes[0].set_xlabel("Number of Clusters")
axes[0].set_ylabel("Inertia")
axes[0].set_xticks(list(k_values))

axes[1].plot(
    list(k_values),
    silhouette_scores,
    marker="o",
    linewidth=2,
    color="green"
)
axes[1].set_title("Silhouette Score by K")
axes[1].set_xlabel("Number of Clusters")
axes[1].set_ylabel("Silhouette Score")
axes[1].set_xticks(list(k_values))

plt.tight_layout()
plt.show()

In [ ]:
OPTIMAL_K = 4 # Set the optimal number of clusters based on evaluation metrics

kmeans = KMeans(
    n_clusters=OPTIMAL_K,
    random_state=RANDOM_STATE,
    n_init=20
)

final_labels = kmeans.fit_predict(X_scaled) # Assign cluster labels to each user based on the final K-Means model

df_results = df_engineered.copy()
df_results["cluster_id"] = final_labels

print("Final K-Means model completed.")

display(
    df_results["cluster_id"]
    .value_counts()
    .sort_index()
    .to_frame("Number of Users")
)

In [ ]:
final_silhouette = silhouette_score(
    X_scaled[sample_indices],
    final_labels[sample_indices]
)

final_davies_bouldin = davies_bouldin_score(
    X_scaled,
    final_labels
)

final_calinski_harabasz = calinski_harabasz_score(
    X_scaled,
    final_labels
)

print("Final Model Evaluation")
print("-" * 35)
print(f"Number of clusters: {OPTIMAL_K}")
print(f"Inertia: {kmeans.inertia_:.2f}")
print(f"Silhouette Score: {final_silhouette:.4f}")
print(f"Davies-Bouldin Score: {final_davies_bouldin:.4f}")
print(f"Calinski-Harabasz Score: {final_calinski_harabasz:.2f}")

In [ ]:
cluster_profile = (
    df_results
    .groupby("cluster_id")[MODEL_FEATURES] # Group the results by cluster_id and select the model features for aggregation
    .mean()                                 # Calculate the mean of each feature for each cluster
    .round(2)                               # Round the mean values to 2 decimal places for better readability
)

cluster_counts = (
    df_results["cluster_id"]
    .value_counts()
    .sort_index()
    .rename("user_count")
)

cluster_profile.insert(
    0,
    "user_count",
    cluster_counts
)

print("Cluster behavior profile:")
display(cluster_profile)

In [ ]:
# All features except recency are considered positive engagement signals.
positive_features = [
    "sessions_per_week",
    "avg_session_duration_min",
    "daily_active_minutes",
    "interaction_depth_per_session",
    "notifications_opened_per_week",
    "ads_clicked_last_30_days",
    "content_downloads",
    "social_shares"
]

cluster_z_profile = (
    X_scaled_df
    .assign(cluster_id=final_labels)
    .groupby("cluster_id")
    .mean()
)

# A high days_since_last_login value means lower engagement.
cluster_engagement_score = (
    cluster_z_profile[positive_features].mean(axis=1)
    - cluster_z_profile["days_since_last_login"]
)

cluster_engagement_score = cluster_engagement_score.sort_values()

print("Cluster engagement ranking:")
display(cluster_engagement_score.to_frame("engagement_score"))

ordered_clusters = cluster_engagement_score.index.tolist()

CLUSTER_NAME_MAP = {
    ordered_clusters[0]: "Low Engagement / At-Risk Users",
    ordered_clusters[1]: "Occasional Users",
    ordered_clusters[2]: "Moderate Engagement Users",
    ordered_clusters[3]: "High Engagement Users"
}

df_results["segment"] = df_results["cluster_id"].map(CLUSTER_NAME_MAP)

print(CLUSTER_NAME_MAP)

In [ ]:
pca = PCA(n_components=2, random_state=RANDOM_STATE)
pca_components = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(
    pca_components,
    columns=["PCA_1", "PCA_2"]
)

pca_df["segment"] = df_results["segment"].values

print(
    "Variance explained by PCA:",
    round(pca.explained_variance_ratio_.sum() * 100, 2),
    "%"
)

plot_sample_size = min(10000, len(pca_df))

pca_plot_df = pca_df.sample(
    n=plot_sample_size,
    random_state=RANDOM_STATE
)

plt.figure(figsize=(12, 8))

sns.scatterplot(
    data=pca_plot_df,
    x="PCA_1",
    y="PCA_2",
    hue="segment",
    alpha=0.65,
    s=35,
    palette="Set1"
)

plt.title("PCA Visualization of User Segments")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.legend(title="Segment")
plt.show()

In [ ]:
for col in ["gender", "country", "device_type", "subscription_type"]:
    print(f"\nCluster distribution by {col}:")
    
    profile_table = pd.crosstab(
        df_results["segment"],
        df_results[col],
        normalize="index"
    ).mul(100).round(2)

    display(profile_table)

In [ ]:
users_by_segment = {}

for segment_name in df_results["segment"].unique():
    user_list = df_results.loc[
        df_results["segment"] == segment_name,
        ID_COLUMN
    ].tolist()

    users_by_segment[segment_name] = user_list

    print(f"\n{segment_name}")
    print("Number of users:", len(user_list))
    print("First 20 user IDs:", user_list[:20])

In [ ]:
business_actions = {
    "High Engagement Users": (
        "Offer loyalty rewards, premium plans, referral benefits, "
        "exclusive features, and early product access."
    ),
    "Moderate Engagement Users": (
        "Send personalized feature suggestions, content recommendations, "
        "and targeted notifications to increase engagement."
    ),
    "Low Engagement / At-Risk Users": (
        "Use retention campaigns, onboarding reminders, discounts, "
        "support outreach, and re-engagement notifications."
    ),
    "Occasional Users": (
        "Send timely reminders, simple feature guides, "
        "and personalized content to build regular usage habits."
    )
}

segment_summary = (
    df_results
    .groupby(["cluster_id", "segment"])
    .size()
    .reset_index(name="number_of_users")
)

segment_summary["business_action"] = (
    segment_summary["segment"].map(business_actions)
)

display(segment_summary)

In [ ]:
plt.figure(figsize=(11, 6))

sns.countplot(
    data=df_results,
    x="segment",
    order=df_results["segment"].value_counts().index,
    palette="Set2"
)

plt.title("Number of Users in Each Segment")
plt.xlabel("User Segment")
plt.ylabel("Number of Users")
plt.xticks(rotation=15)
plt.show()